version: '3'
services:
    mariadb:
        build: requirements/mariadb
        restart: on-failure
    wordpress:
        build: requirements/wordpress
        depends_on:
            - mariadb
        restart: on-failure
