version: '3'
services:
    mariadb:
        build: requirements/mariadb
        container_name: "mariadb"
        image: mariadb
        env_file:
            - .env
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception_network
        restart: on-failure
    wordpress:
        container_name: wordpress
        build: requirements/wordpress
        image: wordpress
        env_file:
            - .env
        volumes:
            - wordpress_files:/wordpress
        networks:
            - inception_network
        depends_on:
            - mariadb
        restart: on-failure
    nginx:
        container_name: nginx
        build: requirements/nginx
        image: nginx
        ports:
            - "443:443"
        volumes:
            - wordpress_files:/wordpress
        networks:
            - inception_network
        depends_on:
            - wordpress
        restart: on-failure
networks:
    inception_network:
        driver: bridge
volumes:
    mariadb_data:
        driver: local
        driver_opts:
            device: /Users/flouta/Desktop/1337/db_data1
            o: bind
            type: none
    wordpress_files:
        driver: local
        driver_opts:
            device: /Users/flouta/Desktop/1337/wp_files_data1
            o: bind
            type: none

