CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};
-- CREATE USER '${ROOT_USER}'@'%' IDENTIFIED BY '${ROOT_PASSWORD}';
-- GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${ROOT_USER}'@'localhost';
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_USER_PASS}';
GRANT ALL ON ${DATABASE_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;

