CREATE DATABASE ${DATABASE_NAME};
CREATE USER '${ROOT_USER}'@'localhost' IDENTIFIED BY '${ROOT_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${ROOT_USER}'@'localhost';
CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_USER_PASS}';
GRANT SELECT, INSERT, UPDATE ON ${DATABASE_NAME}}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;

